extends RefCounted
# Araba Yarışı: tema ve pist verileri.
#
# Yeni pist eklemek: TRACKS listesine bir sözlük ekle. Pist sıralı parçalardan oluşur:
#   {"type": "flat", "len": 1600, "stars": 3}     düz yol (stars: yol üstünde yıldız sayısı)
#   {"type": "hill", "len": 1800, "h": 90}        tepe (h < 0 ise çukur); yumuşak çıkıp iner
#   {"type": "slope", "len": 1400, "h": -60}      yokuş: yol h kadar yükselir (h < 0 ise alçalır)
#   {"type": "puddle"}                            su birikintisi (kısa düz parça ortasında)
#   {"type": "bump"}                              kasis
#   {"type": "ramp", "size": 1, "stars": 3}       rampa (size 1 küçük, 2 büyük); stars havadaki yıldızlar,
#                                                 inişe yetecek düz alan otomatik eklenir
# Uzunluklar piksel; araba en hızlı ~680 px/sn gider. "rivals": rakiplerin ek hızı (0 - 0.05).
# validate() her pistin süresini ve yüksekliklerini kontrol eder; oyun açılırken de çalışır.

const THEMES := {
	"orman": {
		"sky": [Color("8fd0f2"), Color("e3f5f6")],
		"verge": [Color("8fd46c"), Color("6cb857")],
		"road": [Color("a39fae"), Color("8e8a9c")],
		"road_line": Color(1, 1, 1, 0.55),
		"curb": Color("6f6a82"),
		"ground": [Color("7cc35f"), Color("5a9a4a")],
		"ground_dot": Color("4f8c42"),
		"ramp": [Color("e0a86a"), Color("b97c45"), Color("7a4e2c")],
		"decor": ["agac", "cali", "cali", "agac"],
		"decor_gap": [420.0, 820.0],
		"effect": "yaprak",
		"sun": "gunes",
		"puddle": Color(1, 1, 1),
	},
	"col": {
		"sky": [Color("7fc4e6"), Color("ffe6bf")],
		"verge": [Color("f6d49a"), Color("e8bb78")],
		"road": [Color("b9a9a0"), Color("a39288")],
		"road_line": Color(1, 1, 1, 0.5),
		"curb": Color("8a766c"),
		"ground": [Color("f0c27e"), Color("d9a060")],
		"ground_dot": Color("c98e52"),
		"ramp": [Color("e7b77a"), Color("c28a4e"), Color("7e5431")],
		"decor": ["kaktus", "kaya", "kaktus", "kaya"],
		"decor_gap": [520.0, 980.0],
		"effect": "toz",
		"sun": "sicak_gunes",
		"puddle": Color(1, 1, 1),
	},
	"kar": {
		"sky": [Color("a5cdef"), Color("eef5fb")],
		"verge": [Color("ffffff"), Color("e3edf7")],
		"road": [Color("a8aec4"), Color("939ab2")],
		"road_line": Color(1, 1, 1, 0.6),
		"curb": Color("767d99"),
		"ground": [Color("f4f8fc"), Color("d6e2ef")],
		"ground_dot": Color("c3d3e5"),
		"ramp": [Color("b9dcf2"), Color("86b7da"), Color("4f7fa6")],
		"decor": ["cam_agaci", "cam_kucuk", "cam_agaci", "kardan_yigin"],
		"decor_gap": [460.0, 900.0],
		"effect": "kar",
		"sun": "",
		"puddle": Color(0.85, 0.97, 1.0),
	},
	"sehir": {
		"sky": [Color("1b2150"), Color("454a8e")],
		"verge": [Color("4d548e"), Color("40467d")],
		"road": [Color("5d5f80"), Color("4c4e6e")],
		"road_line": Color(1, 0.9, 0.6, 0.55),
		"curb": Color("3a3c5c"),
		"ground": [Color("3b406e"), Color("262a4e")],
		"ground_dot": Color("30355f"),
		"ramp": [Color("ffb45e"), Color("e0853a"), Color("7a3f1c")],
		"decor": ["cali_gece", "cali_gece", "kaya_gece"],
		"decor_gap": [520.0, 980.0],
		"lamp_gap": 820.0,                        # sokak lambaları düzenli aralıkla
		"effect": "yildizlar",
		"sun": "ay",
		"puddle": Color(0.75, 0.8, 1.0),
	},
}

# Harita ve simgelerde her temanın rengi ve simgesi
const THEME_ICON := {"orman": "agac", "col": "kaktus", "kar": "cam_agaci", "sehir": "lamba"}
const THEME_COLOR := {"orman": Color("7cc35f"), "col": Color("f0b465"), "kar": Color("9fc9ec"), "sehir": Color("5a5fa8")}

const TRACKS := [
	# 1 — Orman: neredeyse düz, tek küçük rampa
	{"theme": "orman", "rivals": 0.0, "pieces": [
		{"type": "flat", "len": 1400},
		{"type": "flat", "len": 1600, "stars": 3},
		{"type": "hill", "len": 2200, "h": 50, "stars": 3},
		{"type": "flat", "len": 1200},
		{"type": "puddle"},
		{"type": "flat", "len": 1400, "stars": 3},
		{"type": "hill", "len": 2000, "h": -40},
		{"type": "flat", "len": 1000},
		{"type": "ramp", "size": 1, "stars": 3},
		{"type": "flat", "len": 1400, "stars": 3},
		{"type": "slope", "len": 1800, "h": 50},
		{"type": "flat", "len": 1500},
		{"type": "bump"},
		{"type": "flat", "len": 1600, "stars": 3},
		{"type": "hill", "len": 2200, "h": 60},
		{"type": "flat", "len": 1400, "stars": 3},
		{"type": "slope", "len": 1800, "h": -50},
		{"type": "flat", "len": 1400},
		{"type": "puddle"},
		{"type": "flat", "len": 1600, "stars": 3},
		{"type": "hill", "len": 2000, "h": 50},
		{"type": "hill", "len": 1800, "h": 40, "stars": 3},
		{"type": "flat", "len": 1800, "stars": 3},
	]},
	# 2 — Orman: biraz daha tepe, iki küçük rampa
	{"theme": "orman", "rivals": 0.005, "pieces": [
		{"type": "flat", "len": 1400},
		{"type": "hill", "len": 2000, "h": 70, "stars": 3},
		{"type": "flat", "len": 1000},
		{"type": "ramp", "size": 1, "stars": 3},
		{"type": "flat", "len": 1200, "stars": 3},
		{"type": "hill", "len": 2200, "h": -70},
		{"type": "flat", "len": 900},
		{"type": "puddle"},
		{"type": "flat", "len": 1200, "stars": 3},
		{"type": "slope", "len": 1800, "h": 80},
		{"type": "hill", "len": 2000, "h": 70, "stars": 3},
		{"type": "flat", "len": 1000},
		{"type": "bump"},
		{"type": "flat", "len": 1200, "stars": 3},
		{"type": "slope", "len": 1800, "h": -80},
		{"type": "flat", "len": 900},
		{"type": "ramp", "size": 1, "stars": 3},
		{"type": "flat", "len": 1400, "stars": 3},
		{"type": "hill", "len": 2200, "h": 80},
		{"type": "flat", "len": 1000},
		{"type": "puddle"},
		{"type": "flat", "len": 1400, "stars": 3},
		{"type": "hill", "len": 1800, "h": -50},
		{"type": "slope", "len": 1200, "h": 50},
		{"type": "flat", "len": 1200, "stars": 3},
		{"type": "flat", "len": 1600, "stars": 3},
	]},
	# 3 — Çöl: kum tepeleri, ilk büyük rampa
	{"theme": "col", "rivals": 0.01, "pieces": [
		{"type": "flat", "len": 1400},
		{"type": "hill", "len": 2200, "h": 100, "stars": 3},
		{"type": "flat", "len": 900},
		{"type": "ramp", "size": 1, "stars": 3},
		{"type": "flat", "len": 1000, "stars": 3},
		{"type": "hill", "len": 2400, "h": 110},
		{"type": "flat", "len": 900},
		{"type": "bump"},
		{"type": "flat", "len": 1200, "stars": 3},
		{"type": "slope", "len": 1800, "h": 90},
		{"type": "hill", "len": 2000, "h": -80, "stars": 3},
		{"type": "flat", "len": 900},
		{"type": "ramp", "size": 2, "stars": 4},
		{"type": "flat", "len": 1200, "stars": 3},
		{"type": "slope", "len": 1800, "h": -90},
		{"type": "flat", "len": 900},
		{"type": "puddle"},
		{"type": "flat", "len": 1000, "stars": 3},
		{"type": "hill", "len": 2400, "h": 120},
		{"type": "flat", "len": 900},
		{"type": "bump"},
		{"type": "flat", "len": 1200, "stars": 3},
		{"type": "hill", "len": 2000, "h": 90},
		{"type": "flat", "len": 900},
		{"type": "puddle"},
		{"type": "hill", "len": 2200, "h": -90, "stars": 3},
		{"type": "flat", "len": 700},
		{"type": "flat", "len": 1600, "stars": 3},
	]},
	# 4 — Çöl: üç rampa, daha çok tepe
	{"theme": "col", "rivals": 0.015, "pieces": [
		{"type": "flat", "len": 1400},
		{"type": "hill", "len": 2000, "h": 110, "stars": 3},
		{"type": "flat", "len": 800},
		{"type": "ramp", "size": 1, "stars": 3},
		{"type": "flat", "len": 900},
		{"type": "hill", "len": 2200, "h": -90, "stars": 3},
		{"type": "flat", "len": 800},
		{"type": "bump"},
		{"type": "flat", "len": 900, "stars": 3},
		{"type": "slope", "len": 1600, "h": 100},
		{"type": "flat", "len": 800},
		{"type": "ramp", "size": 2, "stars": 4},
		{"type": "flat", "len": 1000, "stars": 3},
		{"type": "hill", "len": 2400, "h": 130},
		{"type": "flat", "len": 800},
		{"type": "puddle"},
		{"type": "flat", "len": 900, "stars": 3},
		{"type": "slope", "len": 1600, "h": -100},
		{"type": "hill", "len": 2000, "h": 100, "stars": 3},
		{"type": "flat", "len": 800},
		{"type": "ramp", "size": 1, "stars": 3},
		{"type": "flat", "len": 1000, "stars": 3},
		{"type": "bump"},
		{"type": "flat", "len": 900},
		{"type": "hill", "len": 2200, "h": -80},
		{"type": "flat", "len": 800},
		{"type": "ramp", "size": 2, "stars": 4},
		{"type": "hill", "len": 2200, "h": 110, "stars": 3},
		{"type": "flat", "len": 1600, "stars": 3},
	]},
	# 5 — Kar: yokuşlar ve iki büyük rampa
	{"theme": "kar", "rivals": 0.02, "pieces": [
		{"type": "flat", "len": 1400},
		{"type": "slope", "len": 1800, "h": 100, "stars": 3},
		{"type": "flat", "len": 800},
		{"type": "ramp", "size": 2, "stars": 4},
		{"type": "flat", "len": 900, "stars": 3},
		{"type": "hill", "len": 2200, "h": 120},
		{"type": "flat", "len": 800},
		{"type": "puddle"},
		{"type": "flat", "len": 900, "stars": 3},
		{"type": "slope", "len": 1600, "h": -120},
		{"type": "hill", "len": 2000, "h": -90, "stars": 3},
		{"type": "flat", "len": 800},
		{"type": "ramp", "size": 1, "stars": 3},
		{"type": "flat", "len": 900, "stars": 3},
		{"type": "bump"},
		{"type": "flat", "len": 800},
		{"type": "hill", "len": 2400, "h": 140, "stars": 3},
		{"type": "flat", "len": 800},
		{"type": "ramp", "size": 2, "stars": 4},
		{"type": "flat", "len": 900, "stars": 3},
		{"type": "slope", "len": 1800, "h": 90},
		{"type": "flat", "len": 800},
		{"type": "bump"},
		{"type": "flat", "len": 900, "stars": 3},
		{"type": "hill", "len": 2200, "h": 110},
		{"type": "ramp", "size": 1, "stars": 3},
		{"type": "flat", "len": 800},
		{"type": "puddle"},
		{"type": "flat", "len": 800, "stars": 3},
		{"type": "hill", "len": 2400, "h": -120},
		{"type": "flat", "len": 1600, "stars": 3},
	]},
	# 6 — Kar: daha dalgalı, dört rampa
	{"theme": "kar", "rivals": 0.025, "pieces": [
		{"type": "flat", "len": 1400},
		{"type": "hill", "len": 2000, "h": 130, "stars": 3},
		{"type": "flat", "len": 700},
		{"type": "ramp", "size": 1, "stars": 3},
		{"type": "flat", "len": 800, "stars": 3},
		{"type": "slope", "len": 1600, "h": 120},
		{"type": "hill", "len": 1800, "h": -100, "stars": 3},
		{"type": "flat", "len": 700},
		{"type": "ramp", "size": 2, "stars": 4},
		{"type": "flat", "len": 800},
		{"type": "puddle"},
		{"type": "flat", "len": 800, "stars": 3},
		{"type": "hill", "len": 2200, "h": 150},
		{"type": "flat", "len": 700},
		{"type": "bump"},
		{"type": "flat", "len": 800, "stars": 3},
		{"type": "slope", "len": 1600, "h": -130},
		{"type": "flat", "len": 700},
		{"type": "ramp", "size": 2, "stars": 4},
		{"type": "flat", "len": 900, "stars": 3},
		{"type": "hill", "len": 2000, "h": 120},
		{"type": "flat", "len": 700},
		{"type": "bump"},
		{"type": "flat", "len": 800},
		{"type": "hill", "len": 1800, "h": -90, "stars": 3},
		{"type": "flat", "len": 700},
		{"type": "ramp", "size": 1, "stars": 3},
		{"type": "flat", "len": 800},
		{"type": "ramp", "size": 1, "stars": 3},
		{"type": "slope", "len": 1600, "h": 110, "stars": 3},
		{"type": "hill", "len": 2000, "h": -100},
		{"type": "flat", "len": 900},
		{"type": "puddle"},
		{"type": "flat", "len": 1600, "stars": 3},
	]},
	# 7 — Gece şehri: sık rampa ve tepe
	{"theme": "sehir", "rivals": 0.03, "pieces": [
		{"type": "flat", "len": 1400},
		{"type": "hill", "len": 1800, "h": 120, "stars": 3},
		{"type": "flat", "len": 700},
		{"type": "ramp", "size": 2, "stars": 4},
		{"type": "flat", "len": 800, "stars": 3},
		{"type": "hill", "len": 2000, "h": 140},
		{"type": "flat", "len": 700},
		{"type": "puddle"},
		{"type": "flat", "len": 700},
		{"type": "ramp", "size": 1, "stars": 3},
		{"type": "flat", "len": 800, "stars": 3},
		{"type": "slope", "len": 1600, "h": 130},
		{"type": "hill", "len": 1800, "h": -110, "stars": 3},
		{"type": "flat", "len": 700},
		{"type": "bump"},
		{"type": "flat", "len": 700},
		{"type": "ramp", "size": 2, "stars": 4},
		{"type": "flat", "len": 800, "stars": 3},
		{"type": "slope", "len": 1600, "h": -130},
		{"type": "hill", "len": 2000, "h": 150},
		{"type": "flat", "len": 700},
		{"type": "puddle"},
		{"type": "flat", "len": 800, "stars": 3},
		{"type": "hill", "len": 1800, "h": 120},
		{"type": "flat", "len": 700},
		{"type": "ramp", "size": 1, "stars": 3},
		{"type": "flat", "len": 800},
		{"type": "bump"},
		{"type": "flat", "len": 700},
		{"type": "ramp", "size": 2, "stars": 4},
		{"type": "hill", "len": 2000, "h": 140, "stars": 3},
		{"type": "flat", "len": 700},
		{"type": "bump"},
		{"type": "slope", "len": 1600, "h": -120},
		{"type": "flat", "len": 800, "stars": 3},
		{"type": "hill", "len": 1800, "h": 100},
		{"type": "flat", "len": 1600, "stars": 3},
	]},
	# 8 — Gece şehri: en uzun, en çok rampa
	{"theme": "sehir", "rivals": 0.035, "pieces": [
		{"type": "flat", "len": 1400},
		{"type": "hill", "len": 1800, "h": 140, "stars": 3},
		{"type": "flat", "len": 700},
		{"type": "ramp", "size": 2, "stars": 4},
		{"type": "flat", "len": 700, "stars": 3},
		{"type": "slope", "len": 1600, "h": 130},
		{"type": "flat", "len": 700},
		{"type": "ramp", "size": 1, "stars": 3},
		{"type": "flat", "len": 700},
		{"type": "hill", "len": 2000, "h": -120, "stars": 3},
		{"type": "flat", "len": 700},
		{"type": "bump"},
		{"type": "flat", "len": 700, "stars": 3},
		{"type": "hill", "len": 2000, "h": 160},
		{"type": "flat", "len": 700},
		{"type": "ramp", "size": 2, "stars": 4},
		{"type": "flat", "len": 800, "stars": 3},
		{"type": "slope", "len": 1600, "h": -140},
		{"type": "flat", "len": 700},
		{"type": "puddle"},
		{"type": "flat", "len": 700, "stars": 3},
		{"type": "hill", "len": 1800, "h": 130},
		{"type": "flat", "len": 700},
		{"type": "ramp", "size": 1, "stars": 3},
		{"type": "flat", "len": 800, "stars": 3},
		{"type": "hill", "len": 2000, "h": -110},
		{"type": "flat", "len": 700},
		{"type": "bump"},
		{"type": "flat", "len": 700},
		{"type": "ramp", "size": 2, "stars": 4},
		{"type": "flat", "len": 800, "stars": 3},
		{"type": "hill", "len": 1800, "h": 120},
		{"type": "flat", "len": 700},
		{"type": "puddle"},
		{"type": "hill", "len": 2000, "h": 150, "stars": 3},
		{"type": "flat", "len": 700},
		{"type": "ramp", "size": 1, "stars": 3},
		{"type": "flat", "len": 800},
		{"type": "flat", "len": 1600, "stars": 3},
	]},
]


static func theme_of(index: int) -> Dictionary:
	return THEMES[TRACKS[index]["theme"]]


# Her pisti kontrol eder; hataları metin olarak döndürür (boşsa her şey yolunda).
# Asıl ölçümleri pist.gd yapar (yolu kurup uzunluğu, süreyi, yükseklikleri hesaplar).
static func validate(builder_script: Script) -> PackedStringArray:
	var errors := PackedStringArray()
	for i in TRACKS.size():
		var track: Dictionary = TRACKS[i]
		if not THEMES.has(track["theme"]):
			errors.append("pist %d: bilinmeyen tema %s" % [i + 1, track["theme"]])
			continue
		for piece in track["pieces"]:
			if not piece.has("type") or not piece["type"] in ["flat", "hill", "slope", "puddle", "bump", "ramp"]:
				errors.append("pist %d: bilinmeyen parça %s" % [i + 1, str(piece)])
		errors.append_array(builder_script.check_track(i))
	return errors
